name: ComplexesCategories
version: "2020.03.12"
date: 2020-03-12
description: |
    Gap package to create (co)chain complexes category of a given Cap category

authors:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

maintainers:
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

GAP: ">= 4.8"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2019.09.04"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "CAP"
      version: ">= 2020.01.10"
      url: "http://homalg-project.github.io/CAP_project/CAP/"
    - name: "MonoidalCategories"
      version: ">= 2019.08.10"
      url: "http://homalg-project.github.io/CAP_project/MonoidalCategories/"

suggested-pkgs:
    - name: "GeneralizedMorphismsForCAP"
      version: ">= 2019.08.10"
      url: "http://homalg-project.github.io/CAP_project/GeneralizedMorphismsForCAP/"
    - name: "InfiniteLists"
      version: ">= 2017.08.01"

www: https://homalg-project.github.io/ComplexesCategories
readme: README.md
packageinfo: https://homalg-project.github.io/ComplexesCategories/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/ComplexesCategories/releases/download/v2020.03.12/ComplexesCategories-2020.03.12.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Chains, Cochains, MappingCone, MappingCylinder, Homotopy.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Sal20</span>]   <b class='BibAuthor'>Saleh, K.</b>,
     <i class='BibTitle'>ComplexesCategories, Gap package to create (co)chain complexes category of a given Cap category,
             Version 2020.03.12</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/ComplexesCategories">https://homalg-project.github.io/ComplexesCategories</a></span>.
    </p>
    

bibtex: |
    @misc{ ComplexesCategories2020.03.12,
      author =           {Saleh, K.},
      title =            {{ComplexesCategories}, Gap package to create (co)chain complexes category of a given Cap category, {V}ersion 2020.03.12},
      month =            {Mar},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href {https://homalg-project.github.io/ComplexesCategories} {\texttt{https://homalg-project.github.io/}\discretionary {}{}{}\texttt{ComplexesCategories}}},
      keywords =         {Chains; Cochains; MappingCone; MappingCylinder; Homotopy},
      printedkey =       {Sal20}
    }

